# Generated by Django 3.2.5 on 2021-07-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('url_management', '0002_alter_url_short_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('device', models.CharField(choices=[('DE', 'desktop'), ('SP', 'smart_phone')], max_length=4)),
                ('browser', models.CharField(max_length=255)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='url_management.url')),
            ],
        ),
    ]
